### ISSUE TITLE
rm -rf !!!

### ISSUE THREAD

**Issue by hetzge** [nikfot/freshgo#2]
It looks a little bit like the follwing line `cmd := exec.Command("/bin/sh", "-c", "sudo rm -rf "+dir)` deleted my system ?! Not sure, i have to investigate a little bit more but my desktop closed after i had executed freshgo and now it doesent boot with error that things like /sbin/init is missing.

**Comment by nikfot** [comment]
I am sorry for what happened to you, however freshgo is not responsible.
However let's clear this out.
Please let me know what command did you run, if you had go installed to your system prior to running freshgo and at what path. Also please provide me the Linux distro and version you are using.

The specific command runs only for the gopath which cannot be your root folder. Only deleting your root folder could delete your filesystem. However it is a good point that more explicit check should be added.

Let me know.

**Comment by jonoden** [comment]
I had the same issue, deleted my `/usr/local/bin` (I built it for darwin..). I was kicking myself for not code reviewing it before using it. This cleanup function needs to be much safer. Thankfully it was easy for me to recover from it.

**Comment by nikfot** [comment]
@jonoden could you please provide me the path to your go installation, (go binary go source etc) and your darwin version so I can reproduce it.

**Comment by nikfot** [comment]
The only way this could be reproduced is if the GOROOT was set to /usr/local which is wrong. I added checks for this case in this commit so I keep it cloased: https://github.com/nikfot/freshgo/commit/5ac7c3919fc301497bf81be1f88a2675029ded1d

**Comment by jonoden** [comment]
I don't have any hard evidence of what it was set to at the time as I have since recovered and reinstalled Go, but looking over the code (the version I still have pulled at any rate, I haven't pulled from origin since) it does a `which go` then removes `/bin/go` from that path to determine the directly to delete, so it seems there was perhaps a link in `/usr/local/bin` for some reason that took precedence in the PATH.

**Comment by nikfot** [comment]
Yes, as I said above the previous version of Go was probably installed in /usr/local/. I have added more failsafes to this and I will be working on it in the next commits.
